name: training
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
# nfs_mount_enabled: true

hooks:
  post-start:
    - composer: install
    - exec: /var/www/html/db/import-db.sh
    - exec: drush cim -y
    - exec: drush updb
    - exec-host: cp -rf web/sites/example.development.services.yml web/sites/development.services.yml
    - exec: drush cr
    - exec-host: launch
