# Override the web container's standard HTTP_EXPOSE
# to access patternlab on http://training.ddev.site:3000.
version: '3.6'
services:
  web:
    ports:
      - "3000"
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3000:3000
